-- 1) INNER JOIN

CREATE DATABASE JOINING1;
USE JOINING1;

CREATE TABLE STUDENT
(
ID INT PRIMARY KEY,
NAME VARCHAR(255)
);

INSERT INTO STUDENT (ID,NAME)
VALUES
(1,'ASHVIN'),
(2,'SUDHIR'),
(3,'GAYATRI'),
(4,'YOGITA'),
(5,'BARI');


CREATE TABLE COURSE
(
STUDENT_ID INT PRIMARY KEY,
SUB_NAME VARCHAR(255)
);

INSERT INTO COURSE (STUDENT_ID,SUB_NAME)
VALUES
(1,'ENGLISH'),
(2,'MATH'),
(3,'MARATHI'),
(4,'SANSKRIT'),
(5,'BIO');

INSERT INTO COURSE VALUES
(6,'ENGLISH');
 
SELECT *
FROM STUDENT
INNER JOIN COURSE
ON STUDENT.ID=COURSE.STUDENT_ID;

SELECT * 
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID=C.STUDENT_ID;

SELECT * 
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID=C.STUDENT_ID;


SELECT *
FROM STUDENT
INNER JOIN COURSE
ON STUDENT.ID=COURSE.STUDENT_ID;


SELECT * 
FROM STUDENT AS S
LEFT JOIN COURSE AS C
ON S.ID=C.STUDENT_ID
UNION
SELECT * 
FROM STUDENT AS S
RIGHT JOIN COURSE AS C
ON S.ID=C.STUDENT_ID;

-- ------------------------------------------------------------------------

CREATE DATABASE JOINING2;
USE JOINING2;

CREATE TABLE STUDENT
(
ID INT PRIMARY KEY,
NAME VARCHAR(255)
);

INSERT INTO STUDENT (ID,NAME)
VALUES
(1,'ASHVIN'),
(2,'SUDHIR'),
(3,'GAYATRI'),
(4,'YOGITA'),
(5,'BARI');


CREATE TABLE COURSE
(
STUDENT_ID INT PRIMARY KEY,
SUB_NAME VARCHAR(255)
);

INSERT INTO COURSE (STUDENT_ID,SUB_NAME)
VALUES
(1,'ENGLISH'),
(2,'MATH'),
(3,'MARATHI'),
(4,'SANSKRIT');
INSERT INTO COURSE VALUES
(6,'ENGLISH');

SELECT *
FROM STUDENT AS A
LEFT JOIN COURSE AS B
ON A.ID=B.STUDENT_ID
WHERE B.STUDENT_ID  IS null;

SELECT *
FROM STUDENT AS A
RIGHT JOIN COURSE AS B
ON B.STUDENT_ID=A.ID
WHERE A.ID  IS null;


/*
SELECT *
FROM STUDENT AS A
RIGHT JOIN COURSE AS B
ON B.STUDENT_ID=A.ID
WHERE A.ID IS NULL
SELECT *
FROM STUDENT AS A
RIGHT JOIN COURSE AS B
ON B.STUDENT_ID=A.ID
WHERE B.STUDENT_ID IS NULL;
*/

CREATE TABLE EMPLOYEE
(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
ID_MANAGER INT(20)
);

INSERT INTO EMPLOYEE(ID,NAME,ID_MANAGER)
VALUES
(101,'ADNAM',103),
(102,'CRAZY',104),
(103,'AM',NULL),
(104,'NAM',103);

SELECT*FROM EMPLOYEE;

SELECT A.NAME AS MANAGER_NAME,B.NAME
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID = B.ID_MANAGER;

select id 
from employee
union
select id_manager
from employee;
-- ------------------------------------------------------------------------------------------------------

CREATE DATABASE MINOR;
USE MINOR;

CREATE TABLE TABLE1
(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
ADDR VARCHAR(255),
PRN INT(20)
);

INSERT INTO TABLE1(ID,NAME,ADDR,PRN)
VALUES
(1,'ASH','GPP',2021),
(2,'DAS','BHU',2120),
(3,'JAS','WAGH',2001),
(4,'MAD','GOL',2000),
(5,'MEH','FGD',2019);

SELECT * FROM TABLE2;

CREATE TABLE IF NOT EXISTS TABLE2
(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
ADDR VARCHAR(255),
PRN INT(20)
);

INSERT INTO TABLE2(ID,NAME,ADDR,PRN)
VALUES
(11,'ASDH','GPP1',2021),
(12,'DAES','BHU2',2120),
(13,'JADS','WAGH3',2001),
(14,'MSAD','GOL4',2000),
(15,'METH','FGD5',2019);

INSERT INTO TABLE2(ID,NAME,ADDR,PRN)
VALUES
(18,'ASDH','GPP1',2021);

INSERT INTO TABLE2(ID,NAME,ADDR,PRN)
VALUES
(19,'ASDH','GPP1',2021);

INSERT INTO TABLE2(ID,NAME,ADDR,PRN)
VALUES
(20,'ASDH','GPP1',2021);


SELECT * FROM TABLE2;

SELECT PRN
FROM TABLE1
UNION
SELECT PRN
FROM TABLE2;

-- --------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS COLLEGES;
USE COLLEGES;

CREATE TABLE STUDENT
(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(255),
MIDDLE_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
DATE_OF_BIRTH DATE,
AGE INT(15)
);

INSERT INTO STUDENT ( ID , FIRST_NAME , MIDDLE_NAME , LAST_NAME , DATE_OF_BIRTH , AGE )
VALUES
(1,'GAYATRI','SUDHIR','BARI','2005-11-07',18),
(2,'ASHVIN','SUDHIR','BARI','2003-10-07',20),
(3,'YOGITA','SUDHIR','BARI','1986-02-24',38),
(4,'GAYATRI','SUDHIR','BARI','1976-02-12',46);

SELECT * FROM STUDENT;

ALTER table STUDENT
ADD COLUMN MARKS INT(5) NOT NULL DEFAULT 85;

SET SQL_SAFE_UPDATES=0;

UPDATE STUDENT
SET MARKS=78
WHERE ID=4;

SELECT AVG(MARKS)
FROM STUDENT;

SELECT FIRST_NAME , MIDDLE_NAME , LAST_NAME,MARKS
FROM STUDENT
WHERE MARKS > 80;

SELECT FIRST_NAME , MIDDLE_NAME , LAST_NAME,MARKS
FROM STUDENT
WHERE MARKS > (SELECT AVG(MARKS) FROM STUDENT); 


CREATE TABLE ROLL_NUMBER(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT(5)
);

INSERT INTO ROLL_NUMBER(ID,NAME,MARKS)
VALUES
(101,'ANIL',78),
(102,'BHUMIKA',93),
(103,'CHETAN',85),
(104,'CHETAN',96),
(105,'DHRUV',92),
(106,'EMANULE',82);

SELECT ID,NAME
FROM ROLL_NUMBER
WHERE ID % 2 = 0 ; 

SELECT name,ID
FROM ROLL_NUMBER
    WHERE ID IN(
    SELECT ID
    FROM ROLL_NUMBER
    WHERE ID%2=0);


CREATE TABLE ROLL_NUMBER1(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT(5),
GRADE VARCHAR(5),
CITY VARCHAR(20)
);

INSERT INTO ROLL_NUMBER1(ID,NAME,MARKS,GRADE,CITY)
VALUES
(101,'ANIL',78,'A','DELHI'),
(102,'BHUMIKA',93,'B','MUMBAI'),
(103,'CHETAN',85,'C','BANGLORU'),
(104,'CHETAN',96,'A','HAIDRABAD'),
(105,'DHRUV',92,'B','NASIK'),
(106,'EMANULE',82,'D','BHOPAL');

SELECT * 
FROM ROLL_NUMBER1
WHERE CITY='DELHI';

UPDATE ROLL_NUMBER1
SET CITY='MUMBAI'
WHERE ID=104;

SELECT MAX(MARKS)
FROM (SELECT * FROM ROLL_NUMBER1 WHERE CITY='MUMBAI')AS TEMP;

SELECT(SELECT MAX(MARKS) FROM ROLL_NUMBER1),NAME
FROM ROLL_NUMBER1;

CREATE VIEW VIEW1 AS
SELECT ID,NAME,MARKS FROM ROLL_NUMBER1;

SELECT * FROM VIEW1;

SELECT * FROM VIEW1
WHERE MARKS>90;














