CREATE DATABASE RMS_2;
USE RMS_2;

CREATE TABLE PASSENGER
(
P_ID INT,
P_NAME VARCHAR(20),
AGE INT,
GENDER CHAR(10),
TICKET_ID INT(5),
PRN INT(20)
);

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(2,'THOMAS',11,'MALE',153,4213);

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(3,'JORG',21,'MALE',123,213 );

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(4,'JOHN',21,'MALE',123,213 );

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(5,'HARRY',21,'MALE',123,213 );

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(6,'HARRY',21,'MALE',123,213 );

INSERT INTO PASSENGER (P_ID,P_NAME,AGE,GENDER,TICKET_ID,PRN)
VALUES(7,'HARRY',21,'MALE',123,213 );


-- RETRIVE
SELECT P_ID,P_NAME FROM PASSENGER
WHERE GENDER='MALE';

SELECT DISTINCT P_NAME FROM PASSENGER; 

SELECT * FROM PASSENGER ORDER BY P_ID;

SET SQL_SAFE_UPDATES=0;

UPDATE PASSENGER
SET PRN=765
WHERE P_ID=7;

SELECT * FROM PASSENGER;


-- BETWEEN
SELECT * FROM PASSENGER 
WHERE PRN BETWEEN 123 AND 300;

ALTER TABLE PASSENGER
ADD COLUMN MARKS INT; 

-- LIKE OPERATOR
SELECT * FROM PASSENGER 
WHERE GENDER LIKE'F%';

DROP TABLE PASSENGER;

ALTER TABLE PASSENGER
ADD PRIMARY KEY(P_ID);

DESC PASSENGER;  -- IT SHOWS ALL ABOUT THE CONTENT PRESENT IN OUR TABLE

SELECT * FROM PASSENGER;

CREATE TABLE TICKET
(
P_ID INT,
DEPTTIME TIME,
PRN INT(20)
);

DROP TABLE TICKET;

ALTER TABLE PASSENGER
ADD CONSTRAINT FOREIGN KEY(PRN)REFERENCES TICKET(PRN); 






