CREATE DATABASE IF NOT EXISTS COLLEGE_1;
USE COLLEGE_1;

CREATE TABLE STUDENT
(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(255),
MIDDLE_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
DATE_OF_BIRTH DATE,
AGE INT(15)
);

INSERT INTO STUDENT VALUES
(1,'GAYATRI','SUDHIR','BARI','2005-11-07',18);
INSERT INTO STUDENT VALUES
(2,'ASHVIN','SUDHIR','BARI','2003-10-07',20);
INSERT INTO STUDENT VALUES
(3,'YOGITA','SUDHIR','BARI','1986-02-24',38);
INSERT INTO STUDENT VALUES
(4,'GAYATRI','SUDHIR','BARI','1976-02-12',46);
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
ADD COLUMN MARKS INT(5) DEFAULT 85;

ALTER TABLE STUDENT
DROP COLUMN MARKS;

ALTER TABLE STUDENT
ADD COLUMN GRADE VARCHAR(5) DEFAULT 'A';

TRUNCATE TABLE STUDENT;

UPDATE STUDENT
SET MARKS=98
WHERE ID=1;

UPDATE STUDENT
SET MARKS=95
WHERE ID=2;

UPDATE STUDENT
SET MARKS=75
WHERE ID=3;

UPDATE STUDENT
SET MARKS=79
WHERE ID=4;

SET SQL_SAFE_UPDATES=0;

SELECT * FROM STUDENT;

DELETE FROM STUDENT
WHERE MARKS<80;

ALTER TABLE STUDENT
DROP COLUMN GRADE;

