CREATE DATABASE COLLEGE2;
USE COLLEGE2;

CREATE TABLE STUDENT
(
Roll_no INT PRIMARY KEY,
Name VARCHAR(255),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT (ROLL_NO,NAME,MARKS,GRADE,CITY) 
VALUES
(1,'YASH',95,'A','DHARANGAON'),
(2,'ASHVIN',90,'A','JALGAON'),
(3,'JAS',98,'A','JALGAON'),
(4,'MEH',82,'A','BHUSAWAL'),
(5,'TUSHA',19,'A','HARIVITTHAL'),
(6,'AADI',88,'A','PRIMPRALA'),
(7,'MADHU',55,'A','JALGAON');

SELECT * FROM STUDENT;

SELECT ROLL_NO,NAME FROM STUDENT;

SELECT DISTINCT CITY FROM STUDENT;


---------------------------------------------------------------------------------------------------
CREATE TABLE STUDENT2
(
Roll_no INT PRIMARY KEY,
Name VARCHAR(255),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT2 (ROLL_NO,NAME,MARKS,GRADE,CITY) 
VALUES
(1,'YASH',95,'A','DHARANGAON'),
(2,'ASHVIN',90,'B','JALGAON'),
(3,'JAS',98,'A','JALGAON'),
(4,'MEH',82,'A','BHUSAWAL'),
(5,'TUSHA',19,'A','HARIVITTHAL'),
(6,'AADI',88,'A','PRIMPRALA'),
(7,'MADHU',55,'A','JALGAON');

INSERT INTO STUDENT2 VALUES(9,'YASH',95,'A','DHARANGAON');
SELECT DISTINCT CITY FROM STUDENT2;
SELECT * FROM STUDENT2 WHERE MARKS>80;

SELECT * FROM STUDENT2 WHERE MARKS>80 AND CITY='JALGAON';

SELECT * FROM STUDENT2 WHERE MARKS>80 OR CITY='JALGAON';

SELECT* 
FROM STUDENT2
ORDER BY MARKS ASC;

SELECT* 
FROM STUDENT2
ORDER BY CITY ASC;

SELECT MAX(MARKS)
FROM STUDENT2;

SELECT MIN(MARKS)
FROM STUDENT2;

SELECT AVG(MARKS)
FROM STUDENT2;

SELECT SUM(MARKS)
FROM STUDENT2;

SELECT COUNT(MARKS)
FROM STUDENT2;


SELECT CITY,NAME,COUNT(ROLL_NO)
FROM STUDENT2
GROUP BY CITY,NAME;


SELECT CITY,NAME,AVG(ROLL_NO)
FROM STUDENT2
GROUP BY CITY,NAME;

SELECT CITY,AVG(MARKS)
FROM STUDENT2
GROUP BY CITY
ORDER BY CITY;

-- PRACTICE QUESTION

CREATE DATABASE IF NOT EXISTS PAYMENT; 
USE PAYMENT;

CREATE TABLE METHOD
(
CUST_ID INT PRIMARY KEY,
CUSTOMER VARCHAR(255),
MODE VARCHAR(255),
CITY VARCHAR(255) 
);

INSERT INTO METHOD (CUST_ID,CUSTOMER,MODE,CITY)
VALUES
(101,'ASH','NETBANKING','JAL'),
(102,'YASH','CREDIT CARD','DHAR'),
(103,'JAS','DEBIT CARD','JAL'),
(104,'TUSH','NETBANKING','SHIR'),
(105,'DIP','DEBIT CARD','DHAR'),
(106,'RAJ','CREDIT CARD','JAL'),
(107,'RUP','DEBIT CARD','SHIR'),
(108,'GAU','NETBANKING','JAM'),
(109,'DUR','DEBIT CARD','JAM'),
(110,'KESH','CREDIT CARD','JAL');

SELECT MODE,COUNT(CUST_ID)
FROM METHOD
GROUP BY MODE;

-- HAVING CLAUSE---------------------------------------------------------------------------------------

CREATE DATABASE STUDENT;

USE STUDENT;

CREATE TABLE METHOD1
(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(255), 
MARKS INT(20),
GRADE VARCHAR(255),
CITY VARCHAR(255) 
);

INSERT INTO METHOD1 (ROLL_NO,NAME,MARKS,GRADE,CITY)
VALUES
(101,'ASH',96,'A','JAL'),
(102,'YASH',85,'B','DHAR'),
(103,'JAS',89,'B','JAL'),
(104,'TUSH',65,'D','SHIR'),
(105,'DIP',78,'D','DHAR'),
(106,'RAJ',98,'A','JAL'),
(107,'RUP',87,'B','SHIR'),
(108,'GAU',89,'A','JAM'),
(109,'DUR',95,'A','JAM'),
(110,'KESH',92,'A','JAL');

SELECT * FROM METHOD1;

SELECT CITY,COUNT(ROLL_NO)
FROM METHOD1
GROUP BY CITY;

SELECT GRADE,COUNT(ROLL_NO)
FROM METHOD1
GROUP BY GRADE;

SELECT CITY,COUNT(ROLL_NO)
FROM METHOD1
GROUP BY CITY
HAVING MAX(MARKS)>=95;


SELECT NAME
FROM METHOD1 
WHERE GRADE='A'
GROUP BY NAME
HAVING MAX(MARKS)>=90
ORDER BY NAME ASC; 

SET SQL_SAFE_UPDATES=0;

UPDATE METHOD1
SET MARKS=MARKS+1;

SELECT * FROM METHOD1;

UPDATE METHOD1
SET GRADE='A'
WHERE MARKS >= 70;

UPDATE METHOD1
SET GRADE='B'
WHERE MARKS BETWEEN 70 AND 95;

UPDATE METHOD1
SET MARKS=95
WHERE ROLL_NO=101;

DELETE FROM METHOD1
WHERE MARKS < 93;
SELECT * FROM METHOD1; 

DELETE FROM METHOD1;


-- ----------------------------------------------------------------------------------------------------------
CREATE DATABASE DEL;
USE DEL;
CREATE TABLE METHOD1
(
ROLL_NO INT PRIMARY KEY,
NAME VARCHAR(255), 
MARKS INT(20),
GRADE VARCHAR(255),
CITY VARCHAR(255) 
);

INSERT INTO METHOD1 (ROLL_NO,NAME,MARKS,GRADE,CITY)
VALUES
(101,'ASH',96,'A','JAL'),
(102,'YASH',85,'B','DHAR'),
(103,'JAS',89,'B','JAL'),
(104,'TUSH',65,'D','SHIR'),
(105,'DIP',78,'D','DHAR'),
(106,'RAJ',98,'A','JAL'),
(107,'RUP',87,'B','SHIR'),
(108,'GAU',89,'A','JAM'),
(109,'DUR',95,'A','JAM'),
(110,'KESH',92,'A','JAL');

SELECT * FROM METHOD1;
SET SQL_SAFE_UPDATES=0;
DELETE FROM METHOD1
WHERE MARKS >93;
SELECT * FROM METHOD1;

CREATE TABLE dept(
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

INSERT INTO DEPT 
VALUES
(101,'ENGLISH'),
(102,'MATH');
INSERT INTO DEPT VALUES(103,'PHY');

UPDATE DEPT
SET ID=105
WHERE ID=102;


CREATE TABLE TEACHER(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID)REFERENCES dept(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

INSERT INTO TEACHER 
VALUES
(101,'ASH',101),
(102,'JAS',102),
(104,'MADH',103);
SELECT * FROM TEACHER;







