CREATE DATABASE IF NOT EXISTS COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT
(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(255),
MIDDLE_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
DATE_OF_BIRTH DATE,
AGE INT(15)
);

INSERT INTO STUDENT VALUES
(1,'GAYATRI','SUDHIR','BARI','2005-11-07',18);
INSERT INTO STUDENT VALUES
(2,'ASHVIN','SUDHIR','BARI','2003-10-07',20);
INSERT INTO STUDENT VALUES
(3,'YOGITA','SUDHIR','BARI','1986-02-24',38);
INSERT INTO STUDENT VALUES
(4,'GAYATRI','SUDHIR','BARI','1976-02-12',46);
SELECT * FROM STUDENT;

SHOW DATABASES;

SHOW TABLES;

DROP TABLE STUDENT;
DROP DATABASE COLLEGE;

CREATE DATABASE IF NOT EXISTS COLLEGE;
SHOW DATABASES;

------------------------------------------------------------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS NEW1;
USE NEW1;
CREATE TABLE ADMISSION
(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
AGE INT(20)
);

INSERT INTO ADMISSION 
VALUES
(1,'ASHVIN',20);
SELECT * FROM ADMISSION;

-------------------------------------------------------------------------------------------------------------------------------

CREATE DATABASE XYZ;
USE XYZ;

CREATE TABLE EMPLOYEE
(
ID INT PRIMARY KEY,
NAME VARCHAR(255),
SALARY INT(15)
);

INSERT INTO EMPLOYEE 
VALUES
(1,'ADAM',25000),
(2,'BOB',30000),
(3,'CASEY',40000);

SELECT * FROM EMPLOYEE;

CREATE TABLE EMP
(
ID INT,
SLAYARY INT DEFAULT 25000
);

INSERT INTO EMP (ID) VALUES(1);
SELECT * FROM EMP;









